# Homework 2 - Part 3

In [ ]:
#Student Name: Alex Ojemann

#Student ID: 109722375

In [ ]:
#Use the following information to answer Question 1 through Question 5

In [2]:
#RUN THIS CELL FIRST before you answer Questions 1 - 5

from numpy import array
from numpy.linalg import norm

#Suppose we create/define the following arrays

A1 = array([1,-3,4,5])

A2 = array([3,4,5,7])

A3 = array([
[1, 2],
[3, 4],
[5, 6]])

A4 = array([
[1, 2],
[3, 4]])

A5 = array([
[1, 2],
[3, 4],
[5, 6]])

A6 = array([0.5, 0.5])

A7 = array([[3,-5],
           [16,8],
            [21,23]])

In [3]:
#Question 1:

#Write Python code below to find the element-wise division of A3 by A7

A3/A7

array([[ 0.33333333, -0.4       ],
       [ 0.1875    ,  0.5       ],
       [ 0.23809524,  0.26086957]])

In [4]:
#Question 2:

#Write Python code below to find the transpose of A7

A7.T

array([[ 3, 16, 21],
       [-5,  8, 23]])

In [5]:
#Question 3:

#Write Python code below to divide the transpose of A7 by 5

x = A7.T
x/5

array([[ 0.6,  3.2,  4.2],
       [-1. ,  1.6,  4.6]])

In [9]:
#Question 4:

#Write Python code below to find the vector dot product of A1 and A2

A1[0]*A2[0] + A1[1]*A2[1] + A1[2]*A2[2] + A1[3]*A2[3]

46

In [10]:
#Question 5:

#Write Python code below to divide the l1 norm of A1 by the Euclidean norm of A2.

#Do not assign the L1/ Euclidean norms to any object before the division

norm(A1,1)/norm(A2)

1.3065491598369756

In [11]:
#RUN THIS CELL FIRST before you answer Questions 6 - 10

from numpy import array
from numpy.linalg import norm

#Suppose we create/define the following arrays

# matrix-matrix Hadamard product
#element-wise product



B1 = array([
[1, 2, 3],
[4, 5, 6]])



B2 = array([
[1, 2, 3],
[4, 5, 6]])


B3 = array([[2,3],[5,1],[3,4]])

In [12]:
#Question 6

#Write Python code below to find the Hadamard product of B1 and B2

#Do not assign the product to an object


B1 * B2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
#Question 7

#Write Python code below to subtract B2 from B1

B2 - B1

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
#Question 8

#Write Python code below to find the transpose of B2

B2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
#Question 9

#Write Python code below to find the matrix-matrix dot product of B2 and B3

array([array([B2[0,0] * B3[0,0] + B2[0,1] * B3[1,0] + B2[0,2] * B3[2,0],B2[0,0] * B3[0,1] + B2[0,1] * B3[1,1] + B2[0,2] * B3[2,1]]), array([B2[1,0] * B3[0,0] + B2[1,1] * B3[1,0] + B2[1,2] * B3[2,0],B2[1,0] * B3[0,1] + B2[1,1] * B3[1,1] + B2[1,2] * B3[2,1]])])

array([[21, 17],
       [51, 41]])

In [38]:
#Question 10

#Write Python code below to divide B1 by 0.7

B1/0.7


array([[1.42857143, 2.85714286, 4.28571429],
       [5.71428571, 7.14285714, 8.57142857]])