In [ ]:
                                            ###### Homework 3 - Part 3 ###########

In [ ]:
#Note the following:

#1. Each question is worth 1 point
#2. Write your name and student ID below
#3. Remember to save your file and upload to Canvas

In [ ]:
#Student Name: Alex Ojemann

In [ ]:
#Student ID: 109722375

In [2]:
#RUN THIS CELL FIRST TO ANSWER QUESTIONS 1 - 5

import numpy as np
from scipy import linalg
from numpy import array
from numpy import linalg
from numpy.linalg import norm
from numpy.linalg import qr
from numpy.linalg import eig
from math import inf

# define matrix A 
A = np.array([[2, 1, 1],
 [1, 3, 2],
 [1, 0, 0]]) 

#define vector b
b = np.array([4, 5, 6]) 

#define matrix K
K = np.array([ [2., 1., 1.], [1., 3., 2.], [1., 0., 0]]) 


In [5]:
#Question 1

#Suppose you are given the matrix and vector above as a system of linear equations (SLE) in the form Ax = b where x is a vector.

#Write Python code to find vector x

#Write your answer below

x = linalg.solve(A,b)


In [6]:
#Question 2

#Print the vector x you calculated in Question 1

#Write your answer below

x

array([  6.,  15., -23.])

In [8]:
#Question 3


#Write Python code to find the Euclidean norm of vector x in Question 2


#Write your answer below

#sqrt(x[0]*x[0]+x[1]*x[1]+x[2]*x[2])
norm(x)

28.106938645110393

In [9]:
#Question 4

#Write Python code to perform the following:

#1. Decompose matrix K by QR decomposition
#2. Obtain the eigenvalues (values) and eigenvectors(vectors) of matrix K
#3. print Q

#Write your answer below


q,r = qr(K)
values, vectors = eig(K)
q

array([[-0.81649658,  0.27602622, -0.50709255],
       [-0.40824829, -0.89708523,  0.16903085],
       [-0.40824829,  0.34503278,  0.84515425]])

In [10]:
#Question 5


#Write Python code to compute the dot product of values and vectors you obtained in Question 4

#Write your answer below

np.dot(values,vectors)

array([-3.07022286, -0.94049481, -1.45996857])

In [11]:
#RUN THIS CELL FIRST TO ANSWER QUESTIONS 6 - 7

#singular-value decomposition
from numpy import array
from scipy.linalg import svd

# define a matrix Z as follows
Z = array([
[1, 2],
[3, 4],
[5, 6],
[12,-3]])

print(Z)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [12 -3]]


In [13]:
#Question 6

#1. Write Python code to find the singular value decomposition of matrix Z defined above
#2. Print matrix U


#Write your answer below

u,s,vh=svd(Z)
u

array([[-0.08484342, -0.2398591 , -0.38212411, -0.88839764],
       [-0.24413269, -0.47104012, -0.71362907,  0.45744288],
       [-0.40342195, -0.70222114,  0.58614032, -0.02399435],
       [-0.8777537 ,  0.47694266, -0.03397419, -0.03032994]])

In [16]:
#Question 7

#Write Python code to find the scalar multiplication of matrix U by the max norm of vector x you computed in Question 1

#Write your answer below
max(abs(x)) * u


array([[ -1.95139876,  -5.5167592 ,  -8.78885448, -20.43314581],
       [ -5.61505182, -10.83392269, -16.41346856,  10.52118634],
       [ -9.27870489, -16.15108617,  13.48122735,  -0.55186994],
       [-20.18833503,  10.96968107,  -0.78140638,  -0.69758863]])

In [17]:
#RUN THIS CELL FIRST TO ANSWER QUESTIONS 8 - 10

import numpy as np
from scipy import linalg
from numpy import array
from numpy import linalg
from numpy.linalg import norm
from numpy.linalg import qr
from numpy.linalg import eig
from math import inf

# define matrix M 
M = np.array([[12, -1, 41,34],
 [2, 3, -5, 17],
 [4, 6, -7,33],
 [3,5,2,1]]) 

#define matrix D
D = np.array([ [2, 1, 12, -7], [10, -32, 2, 4], [11, 20, 0, 5]]) 

#define vector f
f = np.array([14, 4, -6]) 

#define vector h
h = np.array([1, 4, 2]) 

#define vector o
o = np.array([1, 4, 2]) 

In [18]:
#Question 8


#Write Python code to find the dot product of matrix D and matrix M

#Write your answer below


np.dot(D,M)

array([[  53,   38,  -21,  474],
       [  76,  -74,  564, -134],
       [ 187,   74,  361,  719]])

In [19]:
#Question 9

#Suppose you were asked to confirm if the difference between the Euclidean norm of vector f and the max norm
# of vector h is a positive real number, what Python code would you write to show this?


#Write your answer below

norm(f)-max(abs(h))

11.748015748023622

In [20]:
#Question 10

#What is the value of your result of your answer in Question 9 rounded to two decimal places?

#Write your answer below

11.75

11.75

In [25]:
#RUN THIS CELL FIRST To ANSWER QUESTIONS 11 - 15

import numpy as np
import pandas as pd 

#Obtain dataset
df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/AER/CigarettesB.csv", index_col=0).dropna()
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

#Use random splits as validation strategy for model evaluation
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True,
                                   test_size=0.05, random_state=42)

#import linear regression; obtain instance of linear regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

#Fit linear regression model
lr.fit(X_train, y_train)

#Use linear regression model to predict target using test dataset
y_pred = lr.predict(X_test)

#import some linear regression performance metrics
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("RMSE: ", np.round(rmse, 2))


RMSE:  0.2


In [24]:
#Question 11

#What is the value of the Mean Squared Error (MSE) from the output of RMSE above rounded to 2 decimal places?


#Write your answer below

0.02

0.02

In [ ]:
#Question 12


#1. Record the RMSE value from the running the cell above
#2. Change the value of test_size from 0.20 to 0.05
#3. Run the cell again with test_size = 0.05 and record the new RMSE value
#4. Compare the new RMSE with the original RMSE

#What can you say about the trend of RMSE values for both models?


#Write your answer below

#Old rmse = 0.14
#New rmse = 0.20
#Rmse increases as test size decreases

In [ ]:
#Question 13

#Consider your answer to Question 12. What can you say about the impact of decreasing test_size from 0.20 to 0.05
# on how reliable your model is?

#Write your answer below


#It decreases the reliability because the rmse went up


In [ ]:
#Question 14


#How would you justify your answer in Question 13?

#Write your answer below

#The test data is such a small portion of the overall data (5%) that it's not a
#representative sample

In [ ]:
#Question 15

#How would you fix the issue you raised/identified in your answer in Question 14 above?



#Write your answer below

#Use the conventional test size of between 0.2 and 0.3

In [ ]:
                                          ##### End of Homework 3: Part 3 ####